# Generated by Django 4.2.3 on 2023-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, to='blog.comment'),
        ),
    ]
